# Generated by Django 2.2.3 on 2019-08-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permalinks', '0002_auto_20190817_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permalinks',
            name='old_url',
            field=models.URLField(help_text='This is the URL that will be redirected.<br>Follow Full URL Scheme: <b>https://www.example.com/myapp/mypage.html</b>', max_length=300, unique=True, verbose_name='Old URL'),
        ),
    ]
