# Generated by Django 2.2.10 on 2020-02-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permalinks', '0002_auto_20190821_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permalinks',
            name='new_url',
            field=models.URLField(help_text='This is the URL to which the above URL will be redirected.<br>Follow Full URL Scheme: <b>https://www.example.com/myapp/mypage.html</b>', max_length=500, verbose_name='New URL'),
        ),
        migrations.AlterField(
            model_name='permalinks',
            name='old_url',
            field=models.URLField(help_text='This is the URL that will be redirected.<br>Follow Full URL Scheme: <b>https://www.example.com/myapp/mypage.html</b>', max_length=500, unique=True, verbose_name='Old URL'),
        ),
    ]
